### PR TITLE
Force use of mdbook 0.2.1 as 0.2.2 is broken for now

### PR DESCRIPTION
**Pull request by adamgreig**
See rust-embedded/book#58

### CODE REVIEW

**Comment by jamesmunns** [comment]
Huh, looks like some missing `let _ = ...`s ? Not sure why it started failing on this build.

**Comment by adamgreig** [comment]
I think an updated `cortex-m-semihosting` might be triggering the warning but I'm not sure that's even what's causing the eventual failure, which is that `b7c` isn't appearing in `release.objdump`. I'm investigating...

**Comment by adamgreig** [comment]
Think I found the error in the CI script, testing...

**Comment by adamgreig** [comment]
Ugh, the format of objdump appears to have changed:

In this repository, `ci/logging/app2/dev.objdump`:
```
00000001 l       .log            00000001 Goodbye
00000000 l       .log            00000001 Hello, world!
```

If I run `arm-none-eabi-objdump -t target/thumbv7m-none-eabi/debug/app | grep '\.log'`:
```
00000001 g     O .log   00000001 Goodbye
00000000 g     O .log   00000001 Hello, world!
```

**Comment by adamgreig** [comment]
I believe https://github.com/rust-lang/rust/pull/54414 is to blame.

**Comment by adamgreig** [comment]
Whew. What a pain. Shame we can't have Travis build all the `master`s on a regular basis to catch this sort of test rot.

**Comment by adamgreig** [comment]
@jamesmunns re-r?

**Comment by therealprof** [comment]
@adamgreig 

> Whew. What a pain. Shame we can't have Travis build all the masters on a regular basis to catch this sort of test rot.

Why not? I think most of the repos are already built regularly using a recurring "cron" task.

**Comment by adamgreig** [comment]
Oh, you're quite right. I've set up daily builds for the book repos.

**Pull request merged**
