### PR TITLE
Fix CI: regenerate known-good outputs with latest Rust nightly

### PR DESCRIPTION
**Pull request by adamgreig**
This was a little boring! There aren't any serious changes except to the exceptions app which has changed around a bit; I haven't thoroughly checked the new assembly but don't have any reason to think it's wrong, just the result of much newer LLVM/Rust.

### CODE REVIEW

**Comment by adamgreig** [comment]
Ah, cool, the objdump format has changed between our 1.51 and stable/nightly. I haven't bisected the exact version where it changed; bumping MSRV to 1.59.

**Review by eldruin — DISMISSED** [review]
Ah, great! thank you!
bors r+

**Comment by eldruin** [comment]
Ah, the bors config needs to be updated due to the MSRV change.

**Comment by adamgreig** [comment]
Oops, thanks. Updated.

**Review by eldruin — APPROVED** [review]
Thank you!
bors r+

**Pull request merged**
