### PR TITLE
Update objdump outputs

### PR DESCRIPTION
**Pull request by adamgreig**
Hopefully this fixes CI, let's see.

### CODE REVIEW

**Comment by adamgreig** [comment]
Yay. I removed the beta and stable builds and bumped the MSRV 1.58 to 1.62 because something changed in the output format between those versions. I think it makes sense to just build for a specific version and for nightly rather than all four from before, to help reduce CI breakages for unrelated PRs.

**Review by eldruin — DISMISSED** [review]
Thank you!
bors r+

**Comment by adamgreig** [comment]
The nightly output broke overnight :sob: and I forgot to tell bors about the change in Rust version. Hopefully it sticks this time.

**Review by eldruin — APPROVED** [review]
Alright, let's go! Thanks!
bors r+

**Pull request merged**
