### PR TITLE
--no-show-raw-insn with one '-'

### PR DESCRIPTION
**Pull request by alexgoto**
Related issue #83

### CODE REVIEW

**Comment by adamgreig** [comment]
Thanks! It looks like `-print-imm-hex` needs two dashes too?

**Comment by alexgoto** [comment]
> Thanks! It looks like `-print-imm-hex` needs two dashes too?

Checked again. Yes it is.

**Review by adamgreig — APPROVED** [review]
thanks!

bors r+

**Comment by adamgreig** [comment]
Please could you rebase onto master now we've fixed the CI?

**Comment by eldruin** [comment]
bors would test after the merge to master, right?
bors r+

**Pull request merged**
