### PR TITLE
Grammar fixes

### PR DESCRIPTION
**Pull request by robyoung**
Mostly minor grammar fixes and grammar consistency improvements.

### CODE REVIEW

**Review by adamgreig — APPROVED** [review]
Thanks, looks good!

bors merge

**Comment by adamgreig** [comment]
Ah, nuts, this repo is still using Travis CI and it's no longer running. It will need swapping to GHA. I'll try and get to it soon.

**Comment by robyoung** [comment]
@adamgreig I've taken a stab at switching to GitHub actions here https://github.com/rust-embedded/embedonomicon/pull/72
I've stumbled stumbled a bit at actually running it.

**Comment by adamgreig** [comment]
bors retry

**Comment by adamgreig** [comment]
Changes are live, thanks @robyoung!

**Comment by robyoung** [comment]
Thank you!

**Pull request merged**
